s = input('Type something:')
print('The primitive type of this value is', type(s))
print('Is it a num?', s.isnumeric())
print('Are there only spaces?', s.isspace())
print('Is it alphabetic?', s.isalpha())
print('Is it alphanumeric?', s.isalnum())
print('Is it in capitals?', s.isupper())
print('Is it in lowercase?', s.islower())
print('Is it capitalized', s.istitle())
