name = str(input('Type your complete name:')).strip()
divided = name.split()
print('Analysing your name...')
print('Your name in uppercase is: {}'.format(name.upper()))
print('Your name in lowercase is: {}'.format(name.lower()))
print('Your name has a total of {} letters.'.format(len(name.replace(" ", ""))))
# or print('Your name has a total of {} letters.'.format(len(name) - name.count(' ')))
print('Your first name has {} letters.'.format(len(divided[0])))
# or print('Your first name has {} letters.'.format(name.find(' ')))
